export const api = 'https://norma.nomoreparties.space/api'
export const wsFeedUrl = 'wss://norma.nomoreparties.space/orders';

export const fetchStatus = (res: Response) => {
    if (res.ok) {
      return res.json();
    }
    return Promise.reject(`err 01 :: ${res.status}`);
  }

//user actions
export const SET_USER_LOGGED_IN_STATE: 'SET_USER_LOGGED_IN_STATE' = 'SET_USER_LOGGED_IN_STATE';
export const SET_USER_STATE: 'SET_USER_STATE' = 'SET_USER_STATE';
export const DELETE_USER_STATE: 'DELETE_USER_STATE' = 'DELETE_USER_STATE';

export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE: 'GET_USER_FAILURE' = 'GET_USER_FAILURE';

export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE' = 'UPDATE_USER_FAILURE';

export const SET_LOGGING_IN: 'SET_LOGGING_IN' = 'SET_LOGGING_IN';

export const USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS' = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE' = 'USER_LOGIN_FAILURE';
export const SET_LOGIN_STATE: 'SET_LOGIN_STATE' = 'SET_LOGIN_STATE';
export const CLEAR_LOGIN_STATE: 'CLEAR_LOGIN_STATE' = 'CLEAR_LOGIN_STATE';

export const USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS' = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE: 'USER_REGISTRATION_FAILURE' = 'USER_REGISTRATION_FAILURE';
export const SET_REGISTRATION_STATE: 'SET_REGISTRATION_STATE' = 'SET_REGISTRATION_STATE';
export const CLEAR_REGISTRATION_STATE: 'CLEAR_REGISTRATION_STATE' = 'CLEAR_REGISTRATION_STATE';

export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE' = 'FORGOT_PASSWORD_FAILURE';
export const SET_FORGOT_PASSWORD_STATE: 'SET_FORGOT_PASSWORD_STATE' = 'SET_FORGOT_PASSWORD_STATE';
export const CLEAR_FORGOT_PASSWORD_STATE: 'CLEAR_FORGOT_PASSWORD_STATE' = 'CLEAR_FORGOT_PASSWORD_STATE';

export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE' = 'RESET_PASSWORD_FAILURE';
export const SET_RESET_PASSWORD_STATE: 'SET_RESET_PASSWORD_STATE' = 'SET_RESET_PASSWORD_STATE';
export const CLEAR_RESET_PASSWORD_STATE: 'CLEAR_RESET_PASSWORD_STATE' = 'CLEAR_RESET_PASSWORD_STATE';

export const SESSION_TERMINATION_SUCCESS: 'SESSION_TERMINATION_SUCCESS' = 'SESSION_TERMINATION_SUCCESS';
export const SESSION_TERMINATION_FAILURE: 'SESSION_TERMINATION_FAILURE' = 'SESSION_TERMINATION_FAILURE';
export const SET_SESSION_TERMINATION_STATE: 'SET_SESSION_TERMINATION_STATE' = 'SET_SESSION_TERMINATION_STATE';
export const CLEAR_SESSION_TERMINATION_STATE: 'CLEAR_SESSION_TERMINATION_STATE' = 'CLEAR_SESSION_TERMINATION_STATE';


//constructor actions
export const SET_ITEM: 'SET_ITEM' = 'SET_ITEM';
export const REMOVE_ITEM: 'REMOVE_ITEM' = 'REMOVE_ITEM';
export const SEQUENCE_ELEMENTS: 'SEQUENCE_ELEMENTS' = 'SEQUENCE_ELEMENTS';
export const SET_BUN: 'SET_BUN' = 'SET_BUN';
export const CLEAR_INGREDIENTS: 'CLEAR_INGREDIENTS' = 'CLEAR_INGREDIENTS';


//ingridients
export const SET_INGREDIENTS: 'SET_INGREDIENTS' = 'SET_INGREDIENTS'
export const SET_ERR_INGREDIENTS: 'SET_ERR_INGREDIENTS' = 'SET_ERR_INGREDIENTS'
export const SET_LOAD_INGREDIENTS: 'SET_LOAD_INGREDIENTS' = 'SET_LOAD_INGREDIENTS'
export const SET_ACTIVE_TAB: 'SET_ACTIVE_TAB' = 'SET_ACTIVE_TAB'
//export const SET_SELECT_INGRIDIENT: 'SET_SELECT_INGRIDIENT' = 'SET_SELECT_INGRIDIENT'
export const COUNTER_INCRM: 'COUNTER_INCRM' = 'COUNTER_INCRM';
export const COUNTER_DECRM: 'COUNTER_DECRM' = 'COUNTER_DECRM';
export const COUNTERS_RESET: 'COUNTERS_RESET' = 'COUNTERS_RESET';

//current ingredient
export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT';
export const DELETE_CURRENT_INGREDIENT: 'DELETE_CURRENT_INGREDIENT' = 'DELETE_CURRENT_INGREDIENT';
export const SET_INGREDIENT_MODAL_VISIBLE: 'SET_INGREDIENT_MODAL_VISIBLE' = 'SET_INGREDIENT_MODAL_VISIBLE';
export const SET_INGREDIENT_MODAL_INVISIBLE: 'SET_INGREDIENT_MODAL_INVISIBLE' = 'SET_INGREDIENT_MODAL_INVISIBLE'



//otder
export const ORDER_REQUEST_LOAD: 'ORDER_REQUEST_LOAD' = 'ORDER_REQUEST_LOAD';
export const ORDER_REQUEST_ERR: 'ORDER_REQUEST_ERR' = 'ORDER_REQUEST_ERR';
export const SET_ORDER_DATA: 'SET_ORDER_DATA' = 'SET_ORDER_DATA';
export const ORDER_DETAILS_MODAL: 'ORDER_DETAILS_MODAL' = 'ORDER_DETAILS_MODAL';
export const ORDER_DETAILS_RESET: 'ORDER_DETAILS_RESET' = 'ORDER_DETAILS_RESET';

export const ORDER_SUBMIT_SUCCESS: 'ORDER_SUBMIT_SUCCESS' = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_SUBMIT_FAILURE: 'ORDER_SUBMIT_FAILURE' = 'ORDER_SUBMIT_FAILURE';
export const SET_ORDER_MODAL_VISIBLE: 'SET_ORDER_MODAL_VISIBLE' = 'SET_ORDER_MODAL_VISIBLE';
export const SET_ORDER_MODAL_INVISIBLE: 'SET_ORDER_MODAL_INVISIBLE' = 'SET_ORDER_MODAL_INVISIBLE';

//websockets
export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const SET_FEED_MODAL_VISIBILITY: 'SET_FEED_MODAL_VISIBILITY' = 'SET_FEED_MODAL_VISIBILITY';
export const WS_GET_CURRENTFEEDID: 'WS_GET_CURRENTFEEDID' = 'WS_GET_CURRENTFEEDID';